alosStack: ignore non-numeric folders in the data/download dir
+ ignore the non-numeric foldres in the data download directory, similar to stripmapStack, in the following scripts:
   - StackPublic
   - create_cmds
   - read_data

+ create_cmds: print out the number of acquisitions and pairs

+ create_cmds: ignore empty input of `insar.bbox` arg, in addition to the existing None input, otherwise, it causes the following err

```
Traceback (most recent call last):
  File "/home/yunjunz/tools/isce2/src/isce2/contrib/stack/alosStack/geocode.py", line 72, in <module>
    bbox = [float(x) for x in bbox.split('/')]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yunjunz/tools/isce2/src/isce2/contrib/stack/alosStack/geocode.py", line 72, in <listcomp>
    bbox = [float(x) for x in bbox.split('/')]
            ^^^^^^^^
ValueError: could not convert string to float: ''
```